name: 3Gen
favicon: null
layout_spectrum: 0.6769578126259148
typography_spectrum: 0.53768
title: 3Gen.Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
